name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run pytest suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: sudo apt-get install -y librdkafka-dev
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install faker==24.4.0 confluent-kafka==2.3.0 pytest==8.1.1
      - name: Run tests
        run: pytest tests/ -v --tb=short

  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          flake8 data-generator/ api/ \
            --max-line-length=120 \
            --exclude=__pycache__ \
            --extend-ignore=E302,E301,W291,W292,W293,E251,W503

  dbt-validate:
    name: Validate dbt models
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: eduflow_warehouse
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dbt
        run: pip install "dbt-core==1.8.9" "dbt-postgres==1.8.2"
      - name: Create CI profiles.yml
        run: |
          cat > eduflow_dbt/profiles.yml << 'EOF'
          eduflow_dbt:
            target: dev
            outputs:
              dev:
                type: postgres
                host: localhost
                user: airflow
                password: airflow
                port: 5432
                dbname: eduflow_warehouse
                schema: public
                threads: 1
          EOF
      - name: Load seed data
        run: |
          cd eduflow_dbt
          dbt seed --profiles-dir .
      - name: Check seeded tables
        run: |
          PGPASSWORD=airflow psql -h localhost -U airflow -d eduflow_warehouse -c "\dt"
      - name: Run dbt models
        run: |
          cd eduflow_dbt
          dbt run --profiles-dir .
      - name: Run dbt tests
        run: |
          cd eduflow_dbt
          dbt test --profiles-dir .